version: '3.8'

services:
  db:
    image: postgres:14
    env_file:
      - .env.production
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  backend:
    image: widvvm/foodgram_backend:latest
    env_file:
      - .env.production
    volumes:
      - static:/app/staticfiles/
      - media:/app/media/
    depends_on:
      - db
    restart: always
  frontend:
    image: widvvm/foodgram_frontend:latest
    restart: always
  gateway:
    image: widvvm/foodgram_gateway:latest
    ports:
      - "8000:80"
    volumes:
      - static:/app/staticfiles/
      - media:/app/media/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  static:
  media:
  pg_data: