FROM node:18-alpine AS frontend-build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci --legacy-peer-deps
COPY frontend/ .
RUN npm run build

FROM nginx:1.25-alpine
COPY infra/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=frontend-build /app/build/ /usr/share/nginx/html/