services:
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - foodgram_default
  backend:
    image: ${DOCKER_USERNAME}/foodgram_backend:latest
    env_file:
      - .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    restart: always
    networks:
      - foodgram_default
  frontend:
    image: ${DOCKER_USERNAME}/foodgram_frontend:latest
    volumes:
      - frontend_static:/usr/share/nginx/html
    restart: always
    networks:
      - foodgram_default
  nginx:
    image: ${DOCKER_USERNAME}/foodgram_nginx:latest
    ports:
      - "80:80"
    volumes:
      - static:/app/static/
      - media:/app/media/
      - frontend_static:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - foodgram_default
volumes:
  pg_data:
  static:
  media:
  frontend_static:
networks:
  foodgram_default:
    driver: bridge