services:
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - foodgram_default
  backend:
    image: ${DOCKER_USERNAME}/foodgram_backend:latest
    env_file:
      - .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    restart: always
    networks:
      - foodgram_default
  frontend:
    image: ${DOCKER_USERNAME}/foodgram_frontend:latest
    ports:
      - "3000:3000"
    restart: always
    networks:
      - foodgram_default
  nginx:
    build:
      context: ..
      dockerfile: infra/Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      # общие тома для статики/медиа от бэкенда
      - static:/app/static
      - media:/app/media
volumes:
  pg_data:
  static:
  media:
networks:
  foodgram_default:
    driver: bridge