services:
  db:
    image: postgres:14
    container_name: foodgram-db-1
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foodgram_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ${DOCKER_USERNAME}/foodgram_backend:latest
    container_name: foodgram-backend-1
    env_file:
      - .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    image: ${DOCKER_USERNAME}/foodgram_frontend:latest
    container_name: foodgram-frontend-1
    volumes:
      - static:/app/static/
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: ${DOCKER_USERNAME}/foodgram_nginx:latest
    container_name: foodgram-nginx-1
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/app/static/
      - media:/app/media/
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always

volumes:
  pg_data:
  static:
  media: