services:
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foodgram_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ${DOCKER_USERNAME}/foodgram_backend:latest
    env_file:
      - .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    image: ${DOCKER_USERNAME}/foodgram_frontend:latest
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: ${DOCKER_USERNAME}/foodgram_nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - static:/app/static
      - media:/app/media
    restart: always

volumes:
  pg_data:
  static:
  media: