FROM nginx:1.25-alpine

# ваш конфиг — в nginx.conf (вы его уже правили)
COPY infra/nginx.conf /etc/nginx/nginx.conf

# КЛЮЧЕВОЕ: положить сборку фронта в корень, что вы прописали в nginx.conf
COPY frontend/build/ /usr/share/nginx/html/

# Убрать дефолтный сайт, чтобы не было Welcome page
RUN rm -f /etc/nginx/conf.d/default.conf