# Generated by Django 5.2.5 on 2025-09-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatar-icon.png', null=True, upload_to='images/'),
        ),
    ]
